// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM access_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const invalidateToken = `-- name: InvalidateToken :exec
INSERT INTO access_tokens (token_jti, user_id, expires_at)
VALUES ($1, $2, $3)
`

type InvalidateTokenParams struct {
	TokenJti  string           `json:"token_jti"`
	UserID    int64            `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) InvalidateToken(ctx context.Context, arg InvalidateTokenParams) error {
	_, err := q.db.Exec(ctx, invalidateToken, arg.TokenJti, arg.UserID, arg.ExpiresAt)
	return err
}

const isTokenInvalidated = `-- name: IsTokenInvalidated :one
SELECT EXISTS(SELECT 1 FROM access_tokens WHERE token_jti = $1)
`

func (q *Queries) IsTokenInvalidated(ctx context.Context, tokenJti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenInvalidated, tokenJti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
