// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllJourneys = `-- name: GetAllJourneys :many
SELECT id, title, slug, description, cover_image_url, teacher_name, price, created_at, updated_at
FROM journeys
WHERE deleted_at IS NULL
ORDER BY created_at ASC
`

type GetAllJourneysRow struct {
	ID            int64            `json:"id"`
	Title         string           `json:"title"`
	Slug          string           `json:"slug"`
	Description   pgtype.Text      `json:"description"`
	CoverImageUrl pgtype.Text      `json:"cover_image_url"`
	TeacherName   string           `json:"teacher_name"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllJourneys(ctx context.Context) ([]GetAllJourneysRow, error) {
	rows, err := q.db.Query(ctx, getAllJourneys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllJourneysRow{}
	for rows.Next() {
		var i GetAllJourneysRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImageUrl,
			&i.TeacherName,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
