// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: missions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMissionByID = `-- name: GetMissionByID :one
SELECT
    m.id,
    m.chapter_id,
    m.type,
    m.title,
    m.description,
    m.access_level,
    m.order_index,
    m.created_at,
    m.updated_at,
    c.journey_id
FROM
    missions m
    INNER JOIN chapters c ON m.chapter_id = c.id
WHERE
    m.id = $1
    AND m.deleted_at IS NULL
    AND c.deleted_at IS NULL
`

type GetMissionByIDRow struct {
	ID          int64              `json:"id"`
	ChapterID   int64              `json:"chapter_id"`
	Type        MissionType        `json:"type"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	AccessLevel MissionAccessLevel `json:"access_level"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamp   `json:"created_at"`
	UpdatedAt   pgtype.Timestamp   `json:"updated_at"`
	JourneyID   int64              `json:"journey_id"`
}

func (q *Queries) GetMissionByID(ctx context.Context, id int64) (GetMissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getMissionByID, id)
	var i GetMissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.AccessLevel,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JourneyID,
	)
	return i, err
}

const getRewardByMissionID = `-- name: GetRewardByMissionID :one
SELECT
    id,
    mission_id,
    reward_type,
    reward_value,
    created_at,
    updated_at
FROM
    rewards
WHERE
    mission_id = $1
    AND deleted_at IS NULL
`

type GetRewardByMissionIDRow struct {
	ID          int64            `json:"id"`
	MissionID   int64            `json:"mission_id"`
	RewardType  RewardType       `json:"reward_type"`
	RewardValue int32            `json:"reward_value"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetRewardByMissionID(ctx context.Context, missionID int64) (GetRewardByMissionIDRow, error) {
	row := q.db.QueryRow(ctx, getRewardByMissionID, missionID)
	var i GetRewardByMissionIDRow
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.RewardType,
		&i.RewardValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResourcesByMissionID = `-- name: ListResourcesByMissionID :many
SELECT
    id,
    mission_id,
    resource_type,
    resource_url,
    resource_content,
    content_order,
    duration_seconds,
    created_at,
    updated_at
FROM
    mission_resources
WHERE
    mission_id = $1
    AND deleted_at IS NULL
ORDER BY
    content_order ASC
`

type ListResourcesByMissionIDRow struct {
	ID              int64            `json:"id"`
	MissionID       int64            `json:"mission_id"`
	ResourceType    ResourceType     `json:"resource_type"`
	ResourceUrl     pgtype.Text      `json:"resource_url"`
	ResourceContent pgtype.Text      `json:"resource_content"`
	ContentOrder    int32            `json:"content_order"`
	DurationSeconds pgtype.Int4      `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListResourcesByMissionID(ctx context.Context, missionID int64) ([]ListResourcesByMissionIDRow, error) {
	rows, err := q.db.Query(ctx, listResourcesByMissionID, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesByMissionIDRow{}
	for rows.Next() {
		var i ListResourcesByMissionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.ResourceType,
			&i.ResourceUrl,
			&i.ResourceContent,
			&i.ContentOrder,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
