// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MissionAccessLevel string

const (
	MissionAccessLevelPUBLIC        MissionAccessLevel = "PUBLIC"
	MissionAccessLevelAUTHENTICATED MissionAccessLevel = "AUTHENTICATED"
	MissionAccessLevelPURCHASED     MissionAccessLevel = "PURCHASED"
)

func (e *MissionAccessLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MissionAccessLevel(s)
	case string:
		*e = MissionAccessLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for MissionAccessLevel: %T", src)
	}
	return nil
}

type NullMissionAccessLevel struct {
	MissionAccessLevel MissionAccessLevel `json:"mission_access_level"`
	Valid              bool               `json:"valid"` // Valid is true if MissionAccessLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMissionAccessLevel) Scan(value interface{}) error {
	if value == nil {
		ns.MissionAccessLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MissionAccessLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMissionAccessLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MissionAccessLevel), nil
}

type MissionType string

const (
	MissionTypeVIDEO         MissionType = "VIDEO"
	MissionTypeARTICLE       MissionType = "ARTICLE"
	MissionTypeQUESTIONNAIRE MissionType = "QUESTIONNAIRE"
)

func (e *MissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MissionType(s)
	case string:
		*e = MissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for MissionType: %T", src)
	}
	return nil
}

type NullMissionType struct {
	MissionType MissionType `json:"mission_type"`
	Valid       bool        `json:"valid"` // Valid is true if MissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMissionType) Scan(value interface{}) error {
	if value == nil {
		ns.MissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MissionType), nil
}

type OrderStatus string

const (
	OrderStatusUNPAID  OrderStatus = "UNPAID"
	OrderStatusPAID    OrderStatus = "PAID"
	OrderStatusEXPIRED OrderStatus = "EXPIRED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type ProgressStatus string

const (
	ProgressStatusUNCOMPLETED ProgressStatus = "UNCOMPLETED"
	ProgressStatusCOMPLETED   ProgressStatus = "COMPLETED"
	ProgressStatusDELIVERED   ProgressStatus = "DELIVERED"
)

func (e *ProgressStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgressStatus(s)
	case string:
		*e = ProgressStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgressStatus: %T", src)
	}
	return nil
}

type NullProgressStatus struct {
	ProgressStatus ProgressStatus `json:"progress_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProgressStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgressStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProgressStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgressStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgressStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgressStatus), nil
}

type ResourceType string

const (
	ResourceTypeVIDEO   ResourceType = "VIDEO"
	ResourceTypeARTICLE ResourceType = "ARTICLE"
	ResourceTypeFORM    ResourceType = "FORM"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType `json:"resource_type"`
	Valid        bool         `json:"valid"` // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type RewardType string

const (
	RewardTypeEXPERIENCE RewardType = "EXPERIENCE"
)

func (e *RewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RewardType(s)
	case string:
		*e = RewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for RewardType: %T", src)
	}
	return nil
}

type NullRewardType struct {
	RewardType RewardType `json:"reward_type"`
	Valid      bool       `json:"valid"` // Valid is true if RewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.RewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RewardType), nil
}

type UserRole string

const (
	UserRoleSTUDENT UserRole = "STUDENT"
	UserRoleTEACHER UserRole = "TEACHER"
	UserRoleADMIN   UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AccessToken struct {
	ID            int64            `json:"id"`
	TokenJti      string           `json:"token_jti"`
	UserID        int64            `json:"user_id"`
	ExpiresAt     pgtype.Timestamp `json:"expires_at"`
	InvalidatedAt pgtype.Timestamp `json:"invalidated_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Chapter struct {
	ID         int64            `json:"id"`
	JourneyID  int64            `json:"journey_id"`
	Title      string           `json:"title"`
	OrderIndex int32            `json:"order_index"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Journey struct {
	ID            int64            `json:"id"`
	Title         string           `json:"title"`
	Description   pgtype.Text      `json:"description"`
	CoverImageUrl pgtype.Text      `json:"cover_image_url"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	TeacherName   string           `json:"teacher_name"`
	Slug          string           `json:"slug"`
}

type Mission struct {
	ID          int64              `json:"id"`
	ChapterID   int64              `json:"chapter_id"`
	Title       string             `json:"title"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamp   `json:"created_at"`
	UpdatedAt   pgtype.Timestamp   `json:"updated_at"`
	DeletedAt   pgtype.Timestamp   `json:"deleted_at"`
	Type        MissionType        `json:"type"`
	Description pgtype.Text        `json:"description"`
	AccessLevel MissionAccessLevel `json:"access_level"`
}

type MissionResource struct {
	ID              int64            `json:"id"`
	MissionID       int64            `json:"mission_id"`
	ResourceType    ResourceType     `json:"resource_type"`
	ResourceUrl     pgtype.Text      `json:"resource_url"`
	ContentOrder    int32            `json:"content_order"`
	DurationSeconds pgtype.Int4      `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
	ResourceContent pgtype.Text      `json:"resource_content"`
}

type Order struct {
	ID            int64            `json:"id"`
	OrderNumber   string           `json:"order_number"`
	UserID        int64            `json:"user_id"`
	Status        OrderStatus      `json:"status"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	PaidAt        pgtype.Timestamp `json:"paid_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	// 訂單過期時間（建立時設為 created_at + 3天）
	ExpiredAt pgtype.Timestamp `json:"expired_at"`
}

type OrderItem struct {
	ID            int64            `json:"id"`
	OrderID       int64            `json:"order_id"`
	JourneyID     int64            `json:"journey_id"`
	Quantity      int32            `json:"quantity"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}

type RefreshToken struct {
	ID        int64            `json:"id"`
	TokenJti  string           `json:"token_jti"`
	UserID    int64            `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Reward struct {
	ID          int64            `json:"id"`
	MissionID   int64            `json:"mission_id"`
	RewardType  RewardType       `json:"reward_type"`
	RewardValue int32            `json:"reward_value"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	ID               int64            `json:"id"`
	Username         string           `json:"username"`
	PasswordHash     string           `json:"password_hash"`
	Role             UserRole         `json:"role"`
	ExperiencePoints int32            `json:"experience_points"`
	Level            int32            `json:"level"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

type UserJourney struct {
	ID          int64            `json:"id"`
	UserID      int64            `json:"user_id"`
	JourneyID   int64            `json:"journey_id"`
	OrderID     int64            `json:"order_id"`
	PurchasedAt pgtype.Timestamp `json:"purchased_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type UserMissionProgress struct {
	ID                   int64            `json:"id"`
	UserID               int64            `json:"user_id"`
	MissionID            int64            `json:"mission_id"`
	WatchPositionSeconds int32            `json:"watch_position_seconds"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	DeletedAt            pgtype.Timestamp `json:"deleted_at"`
	Status               ProgressStatus   `json:"status"`
}
