// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserHasPurchasedJourney = `-- name: CheckUserHasPurchasedJourney :one
SELECT EXISTS(
    SELECT 1 FROM user_journeys
    WHERE user_id = $1 AND journey_id = $2 AND deleted_at IS NULL
) AS has_purchased
`

type CheckUserHasPurchasedJourneyParams struct {
	UserID    int64 `json:"user_id"`
	JourneyID int64 `json:"journey_id"`
}

func (q *Queries) CheckUserHasPurchasedJourney(ctx context.Context, arg CheckUserHasPurchasedJourneyParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasPurchasedJourney, arg.UserID, arg.JourneyID)
	var has_purchased bool
	err := row.Scan(&has_purchased)
	return has_purchased, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_number,
    user_id,
    status,
    original_price,
    discount,
    price,
    expired_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, order_number, user_id, status, original_price, discount, price, created_at, expired_at, paid_at, updated_at
`

type CreateOrderParams struct {
	OrderNumber   string           `json:"order_number"`
	UserID        int64            `json:"user_id"`
	Status        OrderStatus      `json:"status"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	ExpiredAt     pgtype.Timestamp `json:"expired_at"`
}

type CreateOrderRow struct {
	ID            int64            `json:"id"`
	OrderNumber   string           `json:"order_number"`
	UserID        int64            `json:"user_id"`
	Status        OrderStatus      `json:"status"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	ExpiredAt     pgtype.Timestamp `json:"expired_at"`
	PaidAt        pgtype.Timestamp `json:"paid_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.UserID,
		arg.Status,
		arg.OriginalPrice,
		arg.Discount,
		arg.Price,
		arg.ExpiredAt,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.OriginalPrice,
		&i.Discount,
		&i.Price,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    journey_id,
    quantity,
    original_price,
    discount,
    price
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, order_id, journey_id, quantity, original_price, discount, price, created_at
`

type CreateOrderItemParams struct {
	OrderID       int64          `json:"order_id"`
	JourneyID     int64          `json:"journey_id"`
	Quantity      int32          `json:"quantity"`
	OriginalPrice pgtype.Numeric `json:"original_price"`
	Discount      pgtype.Numeric `json:"discount"`
	Price         pgtype.Numeric `json:"price"`
}

type CreateOrderItemRow struct {
	ID            int64            `json:"id"`
	OrderID       int64            `json:"order_id"`
	JourneyID     int64            `json:"journey_id"`
	Quantity      int32            `json:"quantity"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (CreateOrderItemRow, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.JourneyID,
		arg.Quantity,
		arg.OriginalPrice,
		arg.Discount,
		arg.Price,
	)
	var i CreateOrderItemRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.JourneyID,
		&i.Quantity,
		&i.OriginalPrice,
		&i.Discount,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, user_id, status, original_price, discount, price, created_at, expired_at, paid_at, updated_at
FROM orders
WHERE id = $1 AND deleted_at IS NULL
`

type GetOrderByIDRow struct {
	ID            int64            `json:"id"`
	OrderNumber   string           `json:"order_number"`
	UserID        int64            `json:"user_id"`
	Status        OrderStatus      `json:"status"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	ExpiredAt     pgtype.Timestamp `json:"expired_at"`
	PaidAt        pgtype.Timestamp `json:"paid_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.OriginalPrice,
		&i.Discount,
		&i.Price,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, journey_id, quantity, original_price, discount, price, created_at
FROM order_items
WHERE order_id = $1 AND deleted_at IS NULL
`

type GetOrderItemsByOrderIDRow struct {
	ID            int64            `json:"id"`
	OrderID       int64            `json:"order_id"`
	JourneyID     int64            `json:"journey_id"`
	Quantity      int32            `json:"quantity"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.JourneyID,
			&i.Quantity,
			&i.OriginalPrice,
			&i.Discount,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpaidOrderByUserAndJourney = `-- name: GetUnpaidOrderByUserAndJourney :one
SELECT o.id, o.order_number, o.user_id, o.status, o.original_price, o.discount, o.price, o.created_at, o.expired_at, o.paid_at, o.updated_at
FROM orders o
INNER JOIN order_items oi ON o.id = oi.order_id
WHERE o.user_id = $1 AND oi.journey_id = $2 AND o.status = 'UNPAID' AND o.deleted_at IS NULL
LIMIT 1
`

type GetUnpaidOrderByUserAndJourneyParams struct {
	UserID    int64 `json:"user_id"`
	JourneyID int64 `json:"journey_id"`
}

type GetUnpaidOrderByUserAndJourneyRow struct {
	ID            int64            `json:"id"`
	OrderNumber   string           `json:"order_number"`
	UserID        int64            `json:"user_id"`
	Status        OrderStatus      `json:"status"`
	OriginalPrice pgtype.Numeric   `json:"original_price"`
	Discount      pgtype.Numeric   `json:"discount"`
	Price         pgtype.Numeric   `json:"price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	ExpiredAt     pgtype.Timestamp `json:"expired_at"`
	PaidAt        pgtype.Timestamp `json:"paid_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUnpaidOrderByUserAndJourney(ctx context.Context, arg GetUnpaidOrderByUserAndJourneyParams) (GetUnpaidOrderByUserAndJourneyRow, error) {
	row := q.db.QueryRow(ctx, getUnpaidOrderByUserAndJourney, arg.UserID, arg.JourneyID)
	var i GetUnpaidOrderByUserAndJourneyRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.OriginalPrice,
		&i.Discount,
		&i.Price,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}
