// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserHasPurchasedJourney(ctx context.Context, arg CheckUserHasPurchasedJourneyParams) (bool, error)
	CountOrdersByUserID(ctx context.Context, userID int64) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (CreateOrderItemRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateUserJourney(ctx context.Context, arg CreateUserJourneyParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	ExistsUserByUsername(ctx context.Context, username string) (bool, error)
	GetJourneyByID(ctx context.Context, id int64) (GetJourneyByIDRow, error)
	GetJourneyTitleByID(ctx context.Context, id int64) (string, error)
	GetJourneyTitlesByIDs(ctx context.Context, dollar_1 []int64) ([]GetJourneyTitlesByIDsRow, error)
	GetMissionByID(ctx context.Context, id int64) (GetMissionByIDRow, error)
	GetOrderByID(ctx context.Context, id int64) (GetOrderByIDRow, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error)
	GetOrderItemsByOrderIDs(ctx context.Context, dollar_1 []int64) ([]GetOrderItemsByOrderIDsRow, error)
	GetOrdersByUserID(ctx context.Context, arg GetOrdersByUserIDParams) ([]GetOrdersByUserIDRow, error)
	GetRefreshToken(ctx context.Context, tokenJti string) (RefreshToken, error)
	GetRewardByMissionID(ctx context.Context, missionID int64) (GetRewardByMissionIDRow, error)
	GetUnpaidOrderByUserAndJourney(ctx context.Context, arg GetUnpaidOrderByUserAndJourneyParams) (GetUnpaidOrderByUserAndJourneyRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserJourneysByUserID(ctx context.Context, userID int64) ([]GetUserJourneysByUserIDRow, error)
	GetUserMissionProgress(ctx context.Context, arg GetUserMissionProgressParams) (GetUserMissionProgressRow, error)
	InvalidateToken(ctx context.Context, arg InvalidateTokenParams) error
	IsTokenInvalidated(ctx context.Context, tokenJti string) (bool, error)
	ListChaptersByJourneyID(ctx context.Context, journeyID int64) ([]ListChaptersByJourneyIDRow, error)
	ListJourneys(ctx context.Context) ([]ListJourneysRow, error)
	ListMissionsByChapterIDs(ctx context.Context, dollar_1 []int64) ([]ListMissionsByChapterIDsRow, error)
	ListResourcesByMissionID(ctx context.Context, missionID int64) ([]ListResourcesByMissionIDRow, error)
	ListUserMissionProgressByMissions(ctx context.Context, arg ListUserMissionProgressByMissionsParams) ([]ListUserMissionProgressByMissionsRow, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, tokenJti string) error
	UpdateJourneyPrice(ctx context.Context, arg UpdateJourneyPriceParams) error
	UpdateOrderStatusToPaid(ctx context.Context, id int64) (UpdateOrderStatusToPaidRow, error)
	UpdateUserExperience(ctx context.Context, arg UpdateUserExperienceParams) (UpdateUserExperienceRow, error)
	UpsertUserMissionProgress(ctx context.Context, arg UpsertUserMissionProgressParams) (UpsertUserMissionProgressRow, error)
}

var _ Querier = (*Queries)(nil)
