// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteExpiredTokens(ctx context.Context) error
	ExistsUserByUsername(ctx context.Context, username string) (bool, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	InvalidateToken(ctx context.Context, arg InvalidateTokenParams) error
	IsTokenInvalidated(ctx context.Context, tokenJti string) (bool, error)
}

var _ Querier = (*Queries)(nil)
