// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	ExistsUserByUsername(ctx context.Context, username string) (bool, error)
	GetJourneyByID(ctx context.Context, id int64) (GetJourneyByIDRow, error)
	GetRefreshToken(ctx context.Context, tokenJti string) (RefreshToken, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	InvalidateToken(ctx context.Context, arg InvalidateTokenParams) error
	IsTokenInvalidated(ctx context.Context, tokenJti string) (bool, error)
	ListChaptersByJourneyID(ctx context.Context, journeyID int64) ([]ListChaptersByJourneyIDRow, error)
	ListJourneys(ctx context.Context) ([]ListJourneysRow, error)
	ListMissionsByChapterIDs(ctx context.Context, dollar_1 []int64) ([]ListMissionsByChapterIDsRow, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, tokenJti string) error
}

var _ Querier = (*Queries)(nil)
