// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token_jti, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	TokenJti  string           `json:"token_jti"`
	UserID    int64            `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.TokenJti, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token_jti, user_id, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_jti = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenJti string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenJti)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenJti,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW()
WHERE token_jti = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenJti string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenJti)
	return err
}
