// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_mission_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserMissionProgress = `-- name: GetUserMissionProgress :one
SELECT
    COALESCE(p.id, 0) as id,
    $1::bigint as user_id,
    m.id as mission_id,
    COALESCE(p.status, 'UNCOMPLETED'::progress_status) as status,
    COALESCE(p.watch_position_seconds, 0) as watch_position_seconds,
    COALESCE(p.created_at, NOW()) as created_at,
    COALESCE(p.updated_at, NOW()) as updated_at
FROM
    missions m
LEFT JOIN
    user_mission_progress p
    ON m.id = p.mission_id AND p.user_id = $1 AND p.deleted_at IS NULL
WHERE
    m.id = $2
    AND m.deleted_at IS NULL
`

type GetUserMissionProgressParams struct {
	Column1 int64 `json:"column_1"`
	ID      int64 `json:"id"`
}

type GetUserMissionProgressRow struct {
	ID                   int64            `json:"id"`
	UserID               int64            `json:"user_id"`
	MissionID            int64            `json:"mission_id"`
	Status               ProgressStatus   `json:"status"`
	WatchPositionSeconds int32            `json:"watch_position_seconds"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserMissionProgress(ctx context.Context, arg GetUserMissionProgressParams) (GetUserMissionProgressRow, error) {
	row := q.db.QueryRow(ctx, getUserMissionProgress, arg.Column1, arg.ID)
	var i GetUserMissionProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.Status,
		&i.WatchPositionSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserMissionProgressByMissions = `-- name: ListUserMissionProgressByMissions :many
SELECT mission_id, status
FROM user_mission_progress
WHERE user_id = $1
  AND mission_id = ANY($2::bigint[])
  AND deleted_at IS NULL
`

type ListUserMissionProgressByMissionsParams struct {
	UserID     int64   `json:"user_id"`
	MissionIds []int64 `json:"mission_ids"`
}

type ListUserMissionProgressByMissionsRow struct {
	MissionID int64          `json:"mission_id"`
	Status    ProgressStatus `json:"status"`
}

func (q *Queries) ListUserMissionProgressByMissions(ctx context.Context, arg ListUserMissionProgressByMissionsParams) ([]ListUserMissionProgressByMissionsRow, error) {
	rows, err := q.db.Query(ctx, listUserMissionProgressByMissions, arg.UserID, arg.MissionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMissionProgressByMissionsRow{}
	for rows.Next() {
		var i ListUserMissionProgressByMissionsRow
		if err := rows.Scan(&i.MissionID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserMissionProgress = `-- name: UpsertUserMissionProgress :one
INSERT INTO
    user_mission_progress (user_id, mission_id, status, watch_position_seconds, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, NOW(), NOW()) ON CONFLICT (user_id, mission_id)
DO
UPDATE
SET
    status = EXCLUDED.status,
    watch_position_seconds = EXCLUDED.watch_position_seconds,
    updated_at = NOW()
RETURNING
    id,
    user_id,
    mission_id,
    status,
    watch_position_seconds,
    created_at,
    updated_at
`

type UpsertUserMissionProgressParams struct {
	UserID               int64          `json:"user_id"`
	MissionID            int64          `json:"mission_id"`
	Status               ProgressStatus `json:"status"`
	WatchPositionSeconds int32          `json:"watch_position_seconds"`
}

type UpsertUserMissionProgressRow struct {
	ID                   int64            `json:"id"`
	UserID               int64            `json:"user_id"`
	MissionID            int64            `json:"mission_id"`
	Status               ProgressStatus   `json:"status"`
	WatchPositionSeconds int32            `json:"watch_position_seconds"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertUserMissionProgress(ctx context.Context, arg UpsertUserMissionProgressParams) (UpsertUserMissionProgressRow, error) {
	row := q.db.QueryRow(ctx, upsertUserMissionProgress,
		arg.UserID,
		arg.MissionID,
		arg.Status,
		arg.WatchPositionSeconds,
	)
	var i UpsertUserMissionProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.Status,
		&i.WatchPositionSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
