// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_mission_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserMissionProgress = `-- name: GetUserMissionProgress :one
SELECT
    id,
    user_id,
    mission_id,
    status,
    watch_position_seconds,
    created_at,
    updated_at
FROM
    user_mission_progress
WHERE
    user_id = $1
    AND mission_id = $2
    AND deleted_at IS NULL
`

type GetUserMissionProgressParams struct {
	UserID    int64 `json:"user_id"`
	MissionID int64 `json:"mission_id"`
}

type GetUserMissionProgressRow struct {
	ID                   int64            `json:"id"`
	UserID               int64            `json:"user_id"`
	MissionID            int64            `json:"mission_id"`
	Status               ProgressStatus   `json:"status"`
	WatchPositionSeconds int32            `json:"watch_position_seconds"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserMissionProgress(ctx context.Context, arg GetUserMissionProgressParams) (GetUserMissionProgressRow, error) {
	row := q.db.QueryRow(ctx, getUserMissionProgress, arg.UserID, arg.MissionID)
	var i GetUserMissionProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.Status,
		&i.WatchPositionSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserMissionProgress = `-- name: UpsertUserMissionProgress :one
INSERT INTO user_mission_progress (
    user_id,
    mission_id,
    status,
    watch_position_seconds,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, NOW(), NOW()
)
ON CONFLICT (user_id, mission_id)
DO UPDATE SET
    status = EXCLUDED.status,
    watch_position_seconds = EXCLUDED.watch_position_seconds,
    updated_at = NOW()
RETURNING
    id,
    user_id,
    mission_id,
    status,
    watch_position_seconds,
    created_at,
    updated_at
`

type UpsertUserMissionProgressParams struct {
	UserID               int64          `json:"user_id"`
	MissionID            int64          `json:"mission_id"`
	Status               ProgressStatus `json:"status"`
	WatchPositionSeconds int32          `json:"watch_position_seconds"`
}

type UpsertUserMissionProgressRow struct {
	ID                   int64            `json:"id"`
	UserID               int64            `json:"user_id"`
	MissionID            int64            `json:"mission_id"`
	Status               ProgressStatus   `json:"status"`
	WatchPositionSeconds int32            `json:"watch_position_seconds"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertUserMissionProgress(ctx context.Context, arg UpsertUserMissionProgressParams) (UpsertUserMissionProgressRow, error) {
	row := q.db.QueryRow(ctx, upsertUserMissionProgress,
		arg.UserID,
		arg.MissionID,
		arg.Status,
		arg.WatchPositionSeconds,
	)
	var i UpsertUserMissionProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.Status,
		&i.WatchPositionSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
