// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_journeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserJourneysByUserID = `-- name: GetUserJourneysByUserID :many
SELECT
    uj.user_id,
    uj.journey_id,
    uj.order_id,
    uj.purchased_at,
    j.title AS journey_title,
    j.slug AS journey_slug,
    j.cover_image_url,
    j.teacher_name,
    o.order_number
FROM user_journeys uj
INNER JOIN journeys j ON uj.journey_id = j.id
INNER JOIN orders o ON uj.order_id = o.id
WHERE uj.user_id = $1
  AND uj.deleted_at IS NULL
  AND j.deleted_at IS NULL
  AND o.deleted_at IS NULL
  AND o.status = 'PAID'
ORDER BY uj.purchased_at DESC
`

type GetUserJourneysByUserIDRow struct {
	UserID        int64            `json:"user_id"`
	JourneyID     int64            `json:"journey_id"`
	OrderID       int64            `json:"order_id"`
	PurchasedAt   pgtype.Timestamp `json:"purchased_at"`
	JourneyTitle  string           `json:"journey_title"`
	JourneySlug   string           `json:"journey_slug"`
	CoverImageUrl pgtype.Text      `json:"cover_image_url"`
	TeacherName   string           `json:"teacher_name"`
	OrderNumber   string           `json:"order_number"`
}

func (q *Queries) GetUserJourneysByUserID(ctx context.Context, userID int64) ([]GetUserJourneysByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getUserJourneysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserJourneysByUserIDRow{}
	for rows.Next() {
		var i GetUserJourneysByUserIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.JourneyID,
			&i.OrderID,
			&i.PurchasedAt,
			&i.JourneyTitle,
			&i.JourneySlug,
			&i.CoverImageUrl,
			&i.TeacherName,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
